package edu.troy.cs3360.fall2013.team1.brickbreak.engine;
/**
 * This is a simple class that defines a rectangle.
 * The shape of the rectangle is generated by its width and height relative to the origin.
 * The origing is defined as an ordered pair at the top left corner of the rectangle.
 *  
 * @author Dexter Parks
 * @version 1.0
 * @since 2013-11-14
 */
public class Rectangle {
	
	//-----Data Members
	float mX;
	float mY;
	float mWidth;
	float mHeight;
	
	//-----Constructors
	/**
	 * Default constructor. Sets position to (0,0) with a width of 1 and height of 1.
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 */
	public Rectangle() {
		mX = 0;
		mY = 0;
		mWidth = 1;
		mHeight = 1;
	}
	
	/**
	 * Constructor that accepts the position from the top left corner.
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param x X position of rectangle
	 * @param y Y position of rectangle
	 * @param width Width of rectangle
	 * @param height Height of rectangle
	 */
	public Rectangle(float x, float y, float width, float height) {
		mX = x;
		mY = y;
		mWidth = width;
		mHeight = height;
	}

	//-----Getters/Setters
	
	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return float returns the x position
	 */
	public float getX() {
		return mX;
	}

	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.1
	 * @param x float value to set
	 */
	public void setX(float x) {
		mX = x;
	}

	/**
	 * Gets the y position
	 * 
	 * @author Dexter Parks
	 * @version 1.1
	 * @return float returns the y position
	 */
	public float getY() {
		return mY;
	}

	/**
	 * Sets the y position
	 * 
	 * @author Dexter Parks
	 * @version 1.1
	 * @param y float value to set
	 */
	public void setY(float y) {
		mY = y;
	}

	/**
	 * Gets the width
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return int returns the width
	 */
	public float getWidth() {
		return mWidth;
	}
	
	/**
	 * Sets the width
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param width float value to set
	 */
	public void setWidth(float width) {
		mWidth = width;
	}

	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return float returns the height
	 */
	public float getHeight() {
		return mHeight;
	}

	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param width float value to set
	 */
	public void setHeight(float height) {
		mHeight = height;
	}
	
}
