package edu.troy.cs3360.fall2013.team1.brickbreak.engine;
/**
 * This is a simple class that defines a rectangle.
 * The shape of the rectangle is generated by its width and height relative to the origin.
 * The origing is defined as an ordered pair at the top left corner of the rectangle.
 *  
 * @author Dexter Parks
 * @version 1.0
 * @since 2013-11-14
 */
public class Rectangle {
	
	//-----Data Members
	int mX;
	int mY;
	int mWidth;
	int mHeight;
	
	//-----Constructors
	/**
	 * Default constructor. Sets position to (0,0) with a width of 1 and height of 1.
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 */
	Rectangle() {
		int mX = 0;
		int mY = 0;
		int mWidth = 1;
		int mHeight = 1;
	}
	
	/**
	 * Constructor that accepts the position from the top left corner.
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param x X position of rectangle
	 * @param y Y position of rectangle
	 * @param width Width of rectangle
	 * @param height Height of rectangle
	 */
	Rectangle(int x, int y, int width, int height) {
		int mX = x;
		int mY = y;
		int mWidth = width;
		int mHeight = height;
	}

	//-----Getters/Setters
	
	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return int returns the x position
	 */
	public int getX() {
		return mX;
	}

	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param x int value to set
	 */
	public void setX(int x) {
		mX = x;
	}

	/**
	 * Gets the y position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return int returns the y position
	 */
	public int getY() {
		return mY;
	}

	/**
	 * Sets the y position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param y int value to set
	 */
	public void setY(int y) {
		mY = y;
	}

	/**
	 * Gets the width
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return int returns the width
	 */
	public int getWidth() {
		return mWidth;
	}
	
	/**
	 * Sets the width
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param width int value to set
	 */
	public void setWidth(int width) {
		mWidth = width;
	}

	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @return int returns the height
	 */
	public int getHeight() {
		return mHeight;
	}

	/**
	 * Gets the x position
	 * 
	 * @author Dexter Parks
	 * @version 1.0
	 * @param width int value to set
	 */
	public void setHeight(int height) {
		mHeight = height;
	}
	
}
